Repository UBC-MDS/census-income-prediction, pull requests merged in 2021-12, with the labels that each got.

#57 Create Makefile and bug fix
  Makefile
  census-income.yaml
  src/eda_script.py
  src/model_evaluation.py
Labels: bug, enhancement

#58 Add narrative about feature selection & Update readme
  README.md
  census-income.yaml
  doc/child/03-Findings.Rmd
  doc/proposal.md
Labels: enhancement

#59 Update Makefile to address the Incompatibility of Windows
  Makefile
Labels: bug

#62 Proofread, modifications and improvements
  README.md
  doc/child/00-Summary.Rmd
  doc/child/01-Introduction.Rmd
  doc/child/02-Datasets.Rmd
  doc/child/03-Findings.Rmd
  doc/child/05-Limitation.Rmd
  doc/proposal.html
  doc/proposal.md
  doc/report.Rmd
  doc/report.md
  results/eval/PR_curve.png
  results/eval/confusion_matrix.csv
  results/eval/model_performance.csv
  results/eval/model_performance_test.csv
  src/model_evaluation.py
Labels: enhancement

#65 updated comments on SHAPing
  doc/child/03-Findings.Rmd
  doc/child/05-Limitation.Rmd
  doc/child/06-Future_Development.Rmd
  doc/report.Rmd
  doc/report.md
Labels: enhancement

#70 Add SHAPing to report and removed typos from some child docs
  doc/child/03-Findings.Rmd
  doc/child/05-Limitation.Rmd
  doc/child/06-Future_Development.Rmd
  doc/report.html
  doc/report.md
Labels: enhancement
