Repository UBC-MDS/census-income-prediction, pull requests merged in 2021-11, with the labels that each got.

#27 Script to read and clean data with exception handling
  src/clean_data.py
Labels: enhancement

#29 Removed '.' form the test_data target column
  src/clean_data.py
Labels: enhancement

#30 Create ML pipeline notebook & Add test data to data/
  data/preprocessed/clean_test.csv
  src/model_building.ipynb
Labels: enhancement

#34 EDA script and tables and figures upload
  results/categorical_feat_plot.png
  results/class_imbalance.png
  results/data_head.csv
  results/data_info.csv
  results/native_country_plot.png
  results/numeric_feature_plot.png
  results/stat_summary_plot.png
  src/eda_script.py
Labels: enhancement

#39 Add graphs & table on finding section, and modify model_performance.py
  artifacts/eval/PR_curve.png
  artifacts/eval/ROC_curve.png
  artifacts/eval/classification_report.csv
  artifacts/eval/confusion_matrix.csv
  artifacts/eval/model_performance.csv
  artifacts/eval/model_performance_test.csv
  census-income.yaml
  doc/child/03-Findings.Rmd
  results/eval/PR_curve.png
  results/eval/ROC_curve.png
  results/eval/model_performance.csv
  src/model_building.py
  src/model_evaluation.py
Labels: enhancement

#43 Final report changes
  README.md
  census-income.yaml
  doc/census_income_refs.bib
  doc/child/00-Summary.Rmd
  doc/child/01-Introduction.Rmd
  doc/child/02-Datasets.Rmd
  doc/report.Rmd
  doc/report.html
Labels: documentation, enhancement

#45 Added links to env file and report
  README.md
Labels: enhancement

#47 added toc and fixed report link
  README.md
  doc/report.Rmd
  doc/report.html
Labels: bug

#49 Changed heading to 'About'
  README.md
  doc/child/02-Datasets.Rmd
  doc/report.html
Labels: documentation

#52 Fixed some typos in Dataset.rmd and added flowchart image
  doc/child/02-Datasets.Rmd
  doc/report.html
  results/flowchart.PNG
Labels: documentation

#53 Added flowchart to README.md
  README.md
Labels: enhancement

#55 Add author on python scripts
  src/clean_data.py
  src/download_data.py
  src/eda_script.py
  src/model_building.py
  src/model_evaluation.py
Labels: enhancement
